name: Purge Cache After CF Deploy

on:
  push:
    branches:
      - master
      - test-cache-purge

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Wait for Cloudflare Pages Deployment
        id: cf-pages
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          project: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
      
      - name: Purge Cloudflare Cache
        if: steps.cf-pages.outputs.success == 'true'
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://widget.gurubase.io/widget.latest.min.js"]}'