name: Purge Cache After CF Deploy

on:
  repository_dispatch:
    types: [cloudflare_pages_deploy]

jobs:
  purge-cache:
    runs-on: ubuntu-latest
    if: github.event.client_payload.branch == 'master'
    steps:
      - name: Wait for 30 seconds
        run: sleep 30
        
      - name: Purge Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{"files":["https://widget.gurubase.io/widget.latest.min.js"]}'